### ISSUE TITLE
 Component remote_command_line Integration 'remote_command_line' not found.

### ISSUE THREAD

**Issue by avico78** [koying/ha-remote-command-line#2]
Trying to use this addon for pulling new homeassitant image and preform an upgrade,
first, is the instructions are correct for adding DiscoveryStream?
anyway, i copy the remote_command_line custom_components/
I added below:

```
remote_command_line:
  fetch_ha_image:
    ssh_user: user
    command_timeout: 900
    command: >
        IMAGE=`docker inspect home-assistant | jq -r '.[0].Config.Image'`; docker pull -q ${IMAGE}
````
I restart HA , when try to execute getting:
```
2022-11-03 09:44:47.129 ERROR (SyncWorker_6) [custom_components.remote_command_line] Command failed: ssh -4 -o ConnectTimeout=3 -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa user@172.17.0.1 'IMAGE=`docker inspect home-assistant | jq -r ''.[0].Config.Image''`; docker pull -q ${IMAGE}'
````
