### ISSUE TITLE
Use predefine parameters

### ISSUE THREAD

**Issue by avico78** [koying/ha-remote-command-line#3]
Would it be possible to support using variable when call the remote_commad_line?
use case - i have predefine command which contorlling the dockers ,
so instead of having sperate command line for all i'd like to be able to use one command,
i.e:
```

service: remote_command_line.update_ha2latest
data: { "docker": "mqtt"}

```
so
```

  update_docker:
    ssh_user: admin
    ssh_host: NAS
    ssh_key: /config/ssh/id_rsa
    docker: {{docker_name}}
    command_timeout: 1300
    command: >
        cd /container-station/bin/docker-compose pull {{docker}} ;/docker-compose up -d --build --no-deps {{docker}}

```
