### ISSUE TITLE
Switch polling is not working...

### ISSUE THREAD

**Issue by GrumpyMeow** [koying/ha-remote-command-line#4]
I have a hard time to get a switch working with remote-command-line. This is my yaml-configuration:
```
switch:
  - platform: remote_command_line
    ssh_user: root
    ssh_host: 192.168.178.2
    ssh_key: /config/id_rsa
    scan_interval: 10
    switches:
      hub_performance:
        polling: true
        command_on: >
          echo "performance" | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor > /dev/null
        command_off: >
          echo "powersave" | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor > /dev/null
        command_state: "[ $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor) == 'performance' ] && exit 0 || exit 1"
```
When i write out the value of "self._polling" it is always "Null".

I suspect these changes need to be made:
```
switches.append(
            CommandSwitch(
                hass,
                config,
                object_id,
                device_config.get(CONF_FRIENDLY_NAME, object_id),
                device_config[CONF_COMMAND_ON],
                device_config[CONF_COMMAND_OFF],
                device_config.get(CONF_COMMAND_STATE),
                value_template,
                device_config.get(CONF_POLLING), <<<< added
            )
        )
```
and
```
        self._value_template = value_template
        self._polling = polling  <<<<  modified
```
